name: nextcart_mobile
description: "NextCart Fashion House mobile app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP client — simple, no setup required
  http: ^1.2.2

  # Image caching with placeholder support
  cached_network_image: ^3.4.1

  # Skeleton loading animation
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
